// Referti/tcEncefalo.js

const additionalText = `
      "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito in urgenza con tecnica spirale, senza mdc. Esame parzialmente inficiato dalla presenza di artefatti da indurimento del fascio.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II.\nArtefatti da indurimento del fascio limitano il giudizio diagnostico.\nPer quanto possibile dire non sicure immagini da riferire ad emorragie endocraniche recenti.\nSi documenta area di ipodensità cortico-sottocorticale, in sede frontale destra, in verosimili esiti di sofferenza tissutale ischemica.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei e delle arterie vertebrali."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito con tecnica spirale multistrato, senza mdc, in urgenza. Classe di dose secondo l' art.161 del D.Lgs 101/2020: II\nPresa visione del precedente esame TC eseguito in data 30/12/2021. Non emorragie endocraniche recenti.\nMultiple ipodensità della sostanza bianca profonda periventricolare, delle corone radiate e centri semiovali, in rapporto a leucoencefalopatia su base vasculopatica cronica.\nNon idrocefalo.\nAmpliamento degli spazi liquorali periencefalici in relazione a fenomeni regressivi parenchimali. Calcificazioni parietali dei sifoni carotidei e delle arterie vertebrali.\nNon rime di frattura del neurocranio.\nIperostosi frontale interna.\nEmatoma sub-galeale in sede parietale destra (spessore 11 mm)."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito in urgenza con tecnica spirale, senza mdc. Classe di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nMultiple ipodensità della sostanza bianca profonda periventricolare, delle corone radiate e centri semiovali in rapporto a leucoencefalopatia su base vasculopatica cronica.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei.\nNon lesioni ossee di sospetto significato fratturativo recente, a carico dei segmenti ossei esaminati."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito in urgenza con tecnica spirale, senza mdc. Presa visione del precedente esame TC eseguito in data 28/07/2022.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon più chiaramente visualizzabile la sfumata iperdensità localizzata nel contesto dell'emiponte destro, descritta al precedente controllo TC.\nNon emorragie endocraniche recenti, in sede sovra-tentoriale.\nStrutture della linea mediana in asse.\nNon idrocefalo.\nInvariati i restanti reperti."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "Esame eseguito in condizioni di base, in regime d'urgenza.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020:II.\nArtefatti da indurimento del fascio derivanti da pregressa embolizzazione di aneurisma intracranico, limitano il giudizio diagnostico.\nNon emorragie endocraniche recenti.\nNon idrocefalo.\nLinea mediana in asse.\nImmagine iperdensa in sede occipitale extrassiale a sinistra, da riferire in prima ipotesi a meningioma calcifico.\nCONCLUSIONI:\nsi invia a valutazione specialistica"
        "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC CRANIO\nREFERTO:\nEsame eseguito in regime d'urgenza, in condizioni di base.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020:II.\nNon emorragie endocraniche recenti.\nFocolai di variabile ipodensità nella sostanza bianca sottocorticale e profonda di entrambi gli emisferi cerebrali, di significato gliotico, probabilmente su base vasculopatica cronica.\nNon idrocefalo.\nLinea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei e delle arterie vertebrali.\nCONCLUSIONI:\nsi invia a valutazione specialistica"
       "referto": "TC ENCEFALO\nEsame eseguito nelle sole condizioni di base in regime di urgenza.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei."
       "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito nelle sole condizioni di base in regime di urgenza.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nMultiple ipodensità della sostanza bianca profonda periventricolare, delle corone radiate e centri semiovali, in rapporto a leucoencefalopatia su base vasculopatica cronica.\nNon idrocefalo.\nAmpliamento degli spazi liquorali periencefalici in relazione a fenomeni regressivi parenchimali.\nCalcificazioni parietali dei sifoni carotidei e delle arterie vertebrali.\nNon rime di frattura del neurocranio.\nIperostosi frontale interna.\nEmatoma sub-galeale in sede parietale destra (spessore 11 mm)."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito in urgenza con tecnica spirale, senza mdc. Classe di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nMultiple ipodensità della sostanza bianca profonda periventricolare, delle corone radiate e centri semiovali in rapporto a leucoencefalopatia su base vasculopatica cronica.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei.\nNon lesioni ossee di sospetto significato fratturativo recente, a carico dei segmenti ossei esaminati."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC ENCEFALO\nEsame eseguito in urgenza con tecnica spirale, senza mdc. Presa visione del precedente esame TC eseguito in data 28/07/2022.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei.\nNon lesioni ossee di sospetto significato fratturativo recente, a carico dei segmenti ossei esaminati."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC CRANIO\nREFERTO:\nEsame eseguito in regime d'urgenza, in condizioni di base.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020:II.\nEmatoma sub-galeale frontale DX (spessore massimo 9 mm).\nNon emorragie endocraniche recenti.\nFalda di igroma subdurale bilaterale.\nMultipli focolai di variabile ipodensità nella sostanza bianca sottocorticale e profonda di entrambi gli emisferi cerebrali, di significato gliotico, probabilmente su base vasculopatica cronica.\nNon idrocefalo.\nSpazi liquorali peri-encefalici più ampi che di norma, in rapporto a fenomeni parenchimali regressivo-atrofici.\nLinea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei e delle arterie vertebrali.\nDiscontinuità corticale del corpo dello sfenoide a destra.\nCONCLUSIONI:\nsi invia a valutazione specialistica"
        "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC CRANIO\nEsame eseguito in condizioni di base, in regime d'urgenza.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II.\nNon emorragie endocraniche recenti.\nSpazi liquorali più ampi che di norma, in rapporto a fenomeni parenchimali regressivo-atrofici, in particolare in sede frontale.\nNon idrocefalo. Strutture della linea mediana in asse.\nCalcificazioni dei sifoni carotidei.\nCONCLUSIONI:\nsi invia a valutazione specialistica."
        "esame": "TC CEREBRALE s/ mdc",
        "referto": "TC CRANIO\nEsame eseguito in condizioni di base, in regime di urgenza.\nPresa visione del precedente esame TC eseguito in data 11/07/2022.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020: II\nNon emorragie endocraniche recenti.\nNon idrocefalo.\nStrutture della linea mediana in asse.\nCalcificazioni parietali dei sifoni carotidei e delle arterie vertebrali.\nRidotto l'ematoma sub-galeale in sede fronto-parietale destra con spessore massimo di 5 mm(vs 8 mm). Non rime di frattura recenti a carico del neurocranio."
         "esame": "TC CEREBRALE s/ mdc",
        "referto": "Esame eseguito in condizioni di base, in regime d'urgenza.\nClasse di dose secondo l' art.161 del D.Lgs 101/2020:II.\nArtefatti da indurimento del fascio derivanti da pregressa embolizzazione di aneurisma intracranico, limitano il giudizio diagnostico.\nNon emorragie endocraniche recenti.\nNon idrocefalo.\nLinea mediana in asse.\nImmagine iperdensa in sede occipitale extrassiale a sinistra, da riferire in prima ipotesi a meningioma calcifico.\nCONCLUSIONI:\nsi invia a valutazione specialistica"


`;

export default additionalText;